trigger:
- main

pool:
  vmImage: ubuntu-latest

strategy:
  matrix:
    Python310:
      python.version: '3.10'
    Python311:
      python.version: '3.11'
    Python312:
      python.version: '3.12'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '(python.version)'
    displayName: 'Use Python $(python.version)'

  - script: echo Hello, world!
    displayName: 'Run a one-line script'


